// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error)
	CreateFeedFollows(ctx context.Context, arg CreateFeedFollowsParams) (FeedFollow, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteFeedFollows(ctx context.Context, arg DeleteFeedFollowsParams) error
	GetFeedFollows(ctx context.Context, userID uuid.UUID) ([]FeedFollow, error)
	GetFeeds(ctx context.Context) ([]Feed, error)
	GetNextFeedstoFetch(ctx context.Context, limit int32) ([]Feed, error)
	GetPostForUser(ctx context.Context, arg GetPostForUserParams) ([]Post, error)
	GetUserByApikey(ctx context.Context, apiKey string) (User, error)
	MarkFeedAsFetched(ctx context.Context, id uuid.UUID) (Feed, error)
}

var _ Querier = (*Queries)(nil)
